web:
  build: .
  ports:
    - "8000:80"
  links:
    - mysql
  volumes:
    - ~/www/Elgg/:/var/www/html/
    - ~/www/elgg-docker/:/elgg-docker/
mysql:
  image: mysql:5.6  
  environment:
    MYSQL_DATABASE: elgg
    MYSQL_ROOT_PASSWORD: 123123