web:
  build: .
  ports:
    - "8000:80"
  links:
    - mysql
  volumes:
    - ~/www/Elgg/:/var/www/html/
    - .:/var/www/html/elgg-docker/
mysql:
  image: mysql:5.7  
  environment:
    MYSQL_DATABASE: elgg
    MYSQL_ROOT_PASSWORD: 123123