web:
  build: .
  ports:
    - "8000:80"
  links:
    - mysql
  volumes:
    - ~/www/Elgg/:/var/www/html/
  environment:
    MYSQL_USER: root
    MYSQL_PASS: root-pass
    ELGG_USERNAME: admin
    ELGG_PASSWORD: admin-pass
mysql:
  image: mysql:5.6  
  environment:
    MYSQL_DATABASE: elgg
    MYSQL_ROOT_PASSWORD: root-pass